import {
  pgTable,
  text,
  integer,
  primaryKey,
  index,
  unique,
  jsonb,
  doublePrecision,
  timestamp,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ============================================
// Phase 0 note: faithful SQLite -> Postgres port.
// Types are kept 1:1 with the previous SQLite schema (text timestamps stored as
// ISO strings, integer booleans 0/1) so app behavior is unchanged. Time
// normalization (timestamptz / starts_at) and geo columns land in later phases.
// Identity PKs use GENERATED BY DEFAULT so the data-migration script can
// preserve existing user IDs; sequences are reset after import.
// ============================================

// Postgres default for text timestamp columns. CURRENT_TIMESTAMP is a
// timestamptz, so it must be cast to text to match the column type.
const nowText = sql`(CURRENT_TIMESTAMP::text)`;

// ============================================
// App-specific tables
// ============================================

export const users = pgTable("users", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  email: text("email").notNull().unique(),
  name: text("name"),
  emailVerified: text("email_verified"), // Required by NextAuth
  image: text("image"), // Required by NextAuth
  isAllowed: integer("is_allowed").default(0), // Allowlist: 1 = can log in
  isAdmin: integer("is_admin").default(0), // Admin: 1 = can access admin dashboard
  createdAt: text("created_at").default(nowText),
});

export const venues = pgTable("venues", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  // --- Phase 1 additive metadata + geo (all nullable; current app ignores them) ---
  operator: text("operator"), // e.g. "Courtside Hubs CIC", "Newham"
  sourceType: text("source_type"), // 'courtside' | 'clubspark' (mirrors VenueType)
  externalId: text("external_id"), // feed facility id (OpenActive facility-use @id / ClubSpark venue id)
  address: text("address"),
  postcode: text("postcode"),
  amenities: jsonb("amenities"),
  bookingUrlTemplate: text("booking_url_template"), // deep-link template for hand-off booking
  active: integer("active").default(1),
  // Plain lat/lng (PostGIS deferred — not available on the Railway image). A
  // btree index on (lat,lng) covers bounding-box map queries at our scale.
  lat: doublePrecision("lat"),
  lng: doublePrecision("lng"),
}, (table) => ({
  // Bounding-box map queries (viewport / radius) without PostGIS.
  latLngIdx: index("idx_venues_lat_lng").on(table.lat, table.lng),
}));

// Individual courts within a venue (OpenActive individual-facility-use).
// Populated by the ingestion adapters in later phases; slots link here as they migrate.
export const courts = pgTable(
  "courts",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    venueId: integer("venue_id")
      .references(() => venues.id, { onDelete: "cascade" })
      .notNull(),
    externalId: text("external_id"), // individual-facility-use @id (stable court identity)
    name: text("name"),
  },
  (table) => ({
    uniqueCourt: unique().on(table.venueId, table.externalId),
    venueIdx: index("idx_courts_venue").on(table.venueId),
  })
);

export const slots = pgTable(
  "slots",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    venueId: integer("venue_id")
      .references(() => venues.id, { onDelete: "cascade" })
      .notNull(),
    date: text("date").notNull(),
    time: text("time").notNull(),
    court: text("court").notNull(),
    status: text("status").notNull(), // 'available', 'booked', 'closed', 'coaching'
    price: text("price"),
    updatedAt: text("updated_at").default(nowText),
    // --- Phase 1 additive feed columns (nullable; populated by ingestion adapters
    // in later phases, then time is normalized end-to-end in Phase 6) ---
    courtId: integer("court_id").references(() => courts.id, { onDelete: "set null" }),
    startsAt: timestamp("starts_at", { withTimezone: true }),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    startMinute: integer("start_minute"), // minutes from midnight, local venue time
    remainingUses: integer("remaining_uses"), // RPDE availability (>0 = bookable)
    maxUses: integer("max_uses"),
    bookingUrl: text("booking_url"),
  },
  (table) => ({
    // Composite unique constraint to prevent duplicate slot entries
    uniqueSlot: unique().on(table.venueId, table.date, table.time, table.court),
    // Index for frequent lookups during scraping
    venueDateTimeIdx: index("idx_slots_venue_date_time").on(table.venueId, table.date, table.time),
  })
);

export const watches = pgTable(
  "watches",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    userId: integer("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    venueId: integer("venue_id").references(() => venues.id, { onDelete: "cascade" }), // null = all venues
    dayTimes: text("day_times"), // JSON object like {"monday":["7pm","8pm"],"tuesday":[],...}
    // Legacy fields for migration compatibility
    weekdayTimes: text("weekday_times"), // DEPRECATED: use dayTimes
    weekendTimes: text("weekend_times"), // DEPRECATED: use dayTimes
    active: integer("active").default(1),
  },
  (table) => ({
    // Index for active watch lookups during notifications
    userActiveIdx: index("idx_watches_user_active").on(table.userId, table.active),
  })
);

export const notificationChannels = pgTable(
  "notification_channels",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    userId: integer("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    type: text("type").notNull(), // 'telegram', 'whatsapp', 'email'
    destination: text("destination").notNull(), // chat_id, phone, or email
    active: integer("active").default(1),
  },
  (table) => ({
    // Prevent duplicate channels
    uniqueChannel: unique().on(table.userId, table.type, table.destination),
    // Index for active channel lookups
    userActiveIdx: index("idx_channels_user_active").on(table.userId, table.active),
  })
);

export const notificationLog = pgTable(
  "notification_log",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    userId: integer("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    channelId: integer("channel_id")
      .references(() => notificationChannels.id, { onDelete: "cascade" })
      .notNull(),
    slotKey: text("slot_key").notNull(), // "venue:date:time:court"
    sentAt: text("sent_at").default(nowText),
  },
  (table) => ({
    // Prevent duplicate notifications
    uniqueNotification: unique().on(table.channelId, table.slotKey),
    // Index for deduplication checks
    channelSlotIdx: index("idx_log_channel_slot").on(table.channelId, table.slotKey),
    // Index for cleanup by date
    sentAtIdx: index("idx_log_sent_at").on(table.sentAt),
  })
);

export const registrationRequests = pgTable(
  "registration_requests",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    email: text("email").notNull(),
    name: text("name"),
    reason: text("reason"), // Why they want access
    status: text("status").default("pending"), // pending | approved | rejected
    createdAt: text("created_at").default(nowText),
    reviewedAt: text("reviewed_at"),
    reviewedBy: integer("reviewed_by").references(() => users.id), // Admin user ID who reviewed
  },
  (table) => ({
    // Index for status lookups
    statusIdx: index("idx_requests_status").on(table.status),
  })
);

// RPDE / interval feed cursors — one row per (source, feed). Persists the RPDE
// `next` cursor so polling resumes where it left off. Replaces scrape_targets
// for feed-based ingestion in a later phase.
export const feedState = pgTable(
  "feed_state",
  {
    id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
    source: text("source").notNull(), // 'openactive' | 'clubspark'
    feed: text("feed").notNull(), // 'facility-uses' | 'individual-facility-use-slots'
    nextCursor: text("next_cursor"),
    lastPolledAt: text("last_polled_at"), // ISO timestamp
  },
  (table) => ({
    uniqueFeed: unique().on(table.source, table.feed),
  })
);

// Tracks scraping schedule for each venue-date combination
export const scrapeTargets = pgTable("scrape_targets", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  venueSlug: text("venue_slug").notNull(),
  date: text("date").notNull(), // YYYY-MM-DD
  lastScrapedAt: text("last_scraped_at"), // ISO timestamp
  nextScrapeAt: text("next_scrape_at"), // ISO timestamp - when next scrape is due
  createdAt: text("created_at").default(nowText),
});

// ============================================
// NextAuth tables (JWT sessions - no sessions table needed)
// ============================================

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(), // email address
    token: text("token").notNull(),
    expires: text("expires").notNull(), // ISO string for Date compatibility
  },
  (table) => ({
    compositePk: primaryKey({ columns: [table.identifier, table.token] }),
  })
);

// ============================================
// Type exports
// ============================================

export type User = typeof users.$inferSelect;
export type Venue = typeof venues.$inferSelect;
export type Court = typeof courts.$inferSelect;
export type FeedState = typeof feedState.$inferSelect;
export type Slot = typeof slots.$inferSelect;
export type Watch = typeof watches.$inferSelect;
export type NotificationChannel = typeof notificationChannels.$inferSelect;
export type NotificationLogEntry = typeof notificationLog.$inferSelect;
export type VerificationToken = typeof verificationTokens.$inferSelect;
export type RegistrationRequest = typeof registrationRequests.$inferSelect;
export type ScrapeTarget = typeof scrapeTargets.$inferSelect;
