[variables]
NIXPACKS_INSTALL_CMD = "npm ci"
NIXPACKS_BUILD_CMD = "npm run build -w @10s/database && cd apps/web && npm run build"
NIXPACKS_START_CMD = "cd apps/web && npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build -w @10s/database",
  "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm start"
