# Multi-service Railway configuration from monorepo root

[[services]]
name = "web"
source = "."

[services.build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build -w @10s/database && cd apps/web && npm run build"
watchPatterns = ["apps/web/**", "packages/database/**"]

[services.deploy]
startCommand = "cd apps/web && npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "scraper"
source = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "apps/scraper/Dockerfile"
dockerContext = "."
watchPatterns = ["apps/scraper/**", "packages/database/**"]

[services.deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10


