[build]
builder = "nixpacks"

[[services]]
name = "web"
source = "apps/web"

[services.build]
buildCommand = "cd apps/web && npm ci && npm run build"
watchPatterns = ["apps/web/**"]

[services.deploy]
startCommand = "cd apps/web && npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Database migration command (optional - can be run manually)
# [services.deploy]
# releaseCommand = "npm run db:push"

[[services]]
name = "scraper"
source = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "apps/scraper/Dockerfile"
dockerContext = "."
watchPatterns = ["apps/scraper/**", "packages/database/**"]

[services.deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
