# Railway configuration for multi-service deployment
# This file defines two services: web (frontend) and scraper (background service)

[[services]]
name = "web"
source = "apps/web"

[services.build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build -w @10s/database && cd apps/web && npm run build"
watchPatterns = ["apps/web/**", "packages/database/**"]

[services.deploy]
startCommand = "cd apps/web && npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

