[build]
builder = "nixpacks"

[[services]]
name = "web"
source = "apps/web"

[services.build]
buildCommand = "npm install && npm run build"
watchPatterns = ["apps/web/**"]

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Database migration command (optional - can be run manually)
# [services.deploy]
# releaseCommand = "npm run db:push"

# Scraper service will be added in Task 5
# [[services]]
# name = "scraper"
# source = "apps/scraper"
