CREATE TABLE "notification_channels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_channels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"type" text NOT NULL,
	"destination" text NOT NULL,
	"active" integer DEFAULT 1,
	CONSTRAINT "notification_channels_user_id_type_destination_unique" UNIQUE("user_id","type","destination")
);
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"channel_id" integer NOT NULL,
	"slot_key" text NOT NULL,
	"sent_at" text DEFAULT (CURRENT_TIMESTAMP::text),
	CONSTRAINT "notification_log_channel_id_slot_key_unique" UNIQUE("channel_id","slot_key")
);
--> statement-breakpoint
CREATE TABLE "registration_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "registration_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text,
	"reason" text,
	"status" text DEFAULT 'pending',
	"created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
	"reviewed_at" text,
	"reviewed_by" integer
);
--> statement-breakpoint
CREATE TABLE "scrape_targets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scrape_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"venue_slug" text NOT NULL,
	"date" text NOT NULL,
	"last_scraped_at" text,
	"next_scrape_at" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);
--> statement-breakpoint
CREATE TABLE "slots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "slots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"venue_id" integer NOT NULL,
	"date" text NOT NULL,
	"time" text NOT NULL,
	"court" text NOT NULL,
	"status" text NOT NULL,
	"price" text,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
	CONSTRAINT "slots_venue_id_date_time_court_unique" UNIQUE("venue_id","date","time","court")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text,
	"email_verified" text,
	"image" text,
	"is_allowed" integer DEFAULT 0,
	"is_admin" integer DEFAULT 0,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "venues" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venues_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "venues_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "verification_tokens" (
	"identifier" text NOT NULL,
	"token" text NOT NULL,
	"expires" text NOT NULL,
	CONSTRAINT "verification_tokens_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "watches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"venue_id" integer,
	"day_times" text,
	"weekday_times" text,
	"weekend_times" text,
	"active" integer DEFAULT 1
);
--> statement-breakpoint
ALTER TABLE "notification_channels" ADD CONSTRAINT "notification_channels_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_channel_id_notification_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."notification_channels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registration_requests" ADD CONSTRAINT "registration_requests_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "slots" ADD CONSTRAINT "slots_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watches" ADD CONSTRAINT "watches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watches" ADD CONSTRAINT "watches_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_channels_user_active" ON "notification_channels" USING btree ("user_id","active");--> statement-breakpoint
CREATE INDEX "idx_log_channel_slot" ON "notification_log" USING btree ("channel_id","slot_key");--> statement-breakpoint
CREATE INDEX "idx_log_sent_at" ON "notification_log" USING btree ("sent_at");--> statement-breakpoint
CREATE INDEX "idx_requests_status" ON "registration_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_slots_venue_date_time" ON "slots" USING btree ("venue_id","date","time");--> statement-breakpoint
CREATE INDEX "idx_watches_user_active" ON "watches" USING btree ("user_id","active");