CREATE TABLE "courts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "courts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"venue_id" integer NOT NULL,
	"external_id" text,
	"name" text,
	CONSTRAINT "courts_venue_id_external_id_unique" UNIQUE("venue_id","external_id")
);
--> statement-breakpoint
CREATE TABLE "feed_state" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feed_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"feed" text NOT NULL,
	"next_cursor" text,
	"last_polled_at" text,
	CONSTRAINT "feed_state_source_feed_unique" UNIQUE("source","feed")
);
--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "court_id" integer;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "starts_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "ends_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "start_minute" integer;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "remaining_uses" integer;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "max_uses" integer;--> statement-breakpoint
ALTER TABLE "slots" ADD COLUMN "booking_url" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "operator" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "source_type" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "external_id" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "postcode" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "amenities" jsonb;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "booking_url_template" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "active" integer DEFAULT 1;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "lat" double precision;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "lng" double precision;--> statement-breakpoint
ALTER TABLE "courts" ADD CONSTRAINT "courts_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_courts_venue" ON "courts" USING btree ("venue_id");--> statement-breakpoint
ALTER TABLE "slots" ADD CONSTRAINT "slots_court_id_courts_id_fk" FOREIGN KEY ("court_id") REFERENCES "public"."courts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_venues_lat_lng" ON "venues" USING btree ("lat","lng");